# Project Information
site_name: Best Packages Documentation Hub
site_url: https://bestdocshub.pages.dev/
site_author: Tivadar György Nagy
site_description: >-
    Here, you'll find documentation for a suite of powerful networking and communication packages designed to enhance your Unity projects.

# Repository
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Benedicht/com.tivadar.best.documentation
repo_name: Tivadar/com.tivadar.best.documentation
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2013 - 2023 Tivadar György Nagy<br/>This website contains affiliate links, which means I might receive a commission if you click a link and purchase something through this website. Purchasing assets through these links won’t cost you any extra money!

# Configuration
theme:
    name: material
    
    # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
    custom_dir: overrides
    
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    icon:
        repo: fontawesome/brands/github
    
    features:
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        #- navigation.expand
        #- navigation.sections
        - navigation.indexes
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-pruning
        - navigation.prune
        - toc.follow
        - navigation.top
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
        - search.suggest
        - search.highlight
        - search.share
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/
        - header.autohide
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/
        - navigation.footer
        
        # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
        - content.code.copy
        - content.code.select
        - content.code.annotate
        
        # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
        - content.action.edit
        - content.action.view
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar
        - announce.dismiss
        
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep orange
          accent: amber
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: brown
          accent: deep orange
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
        
# Plugins
plugins:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
    - search
    
    # https://mkdocs-macros-plugin.readthedocs.io/en/latest/
    - macros
    
    # https://squidfunk.github.io/mkdocs-material/reference/images/
    - glightbox:
        auto_caption: true

    # https://github.com/byrnereese/mkdocs-minify-plugin
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
            remove_empty_space: true
            reduce_boolean_attributes: true
    
# Additional Configuration
extra:
    generator: false
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
    social:
        - icon: fontawesome/brands/mastodon
          link: https://mastodon.gamedev.place/@tivadar
        
        - icon: fontawesome/brands/github
          link: https://github.com/benedicht
        
        - icon: fontawesome/brands/discord
          link: https://discord.gg/yD9tXwQ
          
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/tivadargyorgy

    bundles:
        HTTP_off: 25
        SocketIO_off: 50
        SignalR_off: 44
        MQTT_off: 44
        WebSockets_off: 50
        SSE_off: 40
        Ultimate_off: 33
        STOMP_off: 44

# https://squidfunk.github.io/mkdocs-material/customization/#additional-css
extra_css:
  - assets/stylesheets/extra.css

# Extensions
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - md_in_html
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
    - toc:
        permalink: true
        
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables
    - tables
    
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.smartsymbols

    # https://github.com/squidfunk/mkdocs-material/issues/4988
    # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
    - pymdownx.magiclink:
        normalize_issue_symbols: true
        repo_url_shorthand: true
        user: Benedicht
        repo: BestHTTP-Issues
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
    # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
    - pymdownx.highlight:
        pygments_style: rrt
        use_pygments: true
        pygments_lang_class: true
        anchor_linenums: true
        line_spans: __span
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format

    # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
    - pymdownx.tabbed:
        alternate_style: true
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tasklist
    - pymdownx.tasklist:
        custom_checkbox: true