site_name: Best Packages Documentation Hub

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Benedicht/com.tivadar.best.documentation
repo_name: Tivadar/com.tivadar.best.documentation

copyright: Copyright &copy; 2013 - 2023 Tivadar György Nagy

theme:
    name: material
    
    # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
    custom_dir: overrides
    
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    icon:
        repo: fontawesome/brands/github
    
    features:
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        #- navigation.expand
        - navigation.sections
        - navigation.indexes
        - toc.follow
        - navigation.top
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
        - search.suggest
        - search.highlight
        - search.share
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/
        - header.autohide
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/
        - navigation.footer
        
        # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
        - content.code.copy
        - content.code.select
        - content.code.annotate
        
        # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
        - content.action.edit
        - content.action.view
        
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar
        - announce.dismiss
        
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference
    palette:     
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
        
plugins:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
    - search
    
extra:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
    social:
        - icon: fontawesome/brands/mastodon
          link: https://mastodon.gamedev.place/@tivadar
        
        - icon: fontawesome/brands/github
          link: https://github.com/benedicht
        
        - icon: fontawesome/brands/discord
          link: https://discord.gg/yD9tXwQ
          
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/tivadargyorgy
          
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - md_in_html
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
    - toc:
        permalink: true
        
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables
    - tables
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
    - pymdownx.highlight:
        use_pygments: true
        pygments_lang_class: true
        anchor_linenums: true
        line_spans: __span
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences